notifications:
  email: false

language: node_js

node_js:
- '7'

cache:
  directories:
    - node_modules

install:
   - npm i --silent -g @angular/cli

script:
   - npm i --silent
   - ng build --prod --progress=false --base-href $BASE_HREF

deploy:
  - provider: script
    skip_cleanup: true
    script: bin/deploy-gh-pages.sh
    on:
      branch: master
