notifications:
  email: false

language: node_js

node_js:
- '7'

cache:
  directories:
    - node_modules

install:
   - npm i --silent -g @angular/cli
   - npm i --silent -g angular-cli-ghpages

script:
   - npm i --silent
   - ng build --prod --progress=false --base-href https://$GH_USER.github.io/$GH_REPO/

deploy:
  - provider: script
    script: bin/deploy-gh-pages.sh
    on:
      branch: master
